### ISSUE TITLE
图表标题无法出现斜体

### ISSUE THREAD

**Issue by nil-is-lin** [CSUcse/CSUthesis#1]
图和表中无法字体倾斜，\textit 无效，不知道是不是ctex宏包的问题。

**Comment by wf395962475** [comment]
Please double check you latex environment. It work well in Table, Figures and Caption, I have verified all of them. You can try the \emph{}.

**Comment by nil-is-lin** [comment]
OK，尝试在空文档中写确实可以倾斜。不知道我无意中修改了东西还是旧模板没更新导致，重现了问题再说。
