### ISSUE TITLE
2022《学位论文撰写规范》修订

### ISSUE THREAD

**Issue by SusskindGene** [CSUcse/CSUthesis#13]
2022年4月18日，修订后的《中南大学研究生学位论文撰写规范》已发布：
http://oa.its.csu.edu.cn/Home/ReleaseMainText/9CFE8926B13143009D5EB424333AAD6C

主要修改内容如下：
1. “学位论文版权使用授权书”更新；
2. “封面”及“扉页”关于学科专业的表头更新为：一级学科/专业学位类别，二级学科/专业领域；
3.  附件的模板样例进行了更新完善。人文社科类的一级学科/专业学位类别按根据学科专业特点，可在正文添加“页下注”，参考文献可以按文献类型编写（如中文文献、外文文献、其他等）。

劳烦作者做出相应更新，谢谢！

**Comment by wf395962475** [comment]
收到，感谢提醒，我们正在加紧处理。

**Comment by wf395962475** [comment]
已经修订好，请更新使用，如有问题，请及时反馈，Thanks！
