### ISSUE TITLE
成果与致谢格式不对，目录中的点密度有些稀疏

### ISSUE THREAD

**Issue by nil-is-lin** [CSUcse/CSUthesis#5]
被答辩专家指出来的问题。
成果与致谢部分，我将之前的

> % 重新设置正文行间距，因为前置部分设置时候行间距被改过
> \renewcommand*{\baselinestretch}{1.0}   % 几倍行间距
> \setlength{\baselineskip}{20pt}         % 基准行间距

又用了一遍；
目录中的点，我将 _CSUthesis.cls_ 文件500-530行代码中的

> \titlerule*[?em]{$\cdot$}\contentspage

进行了修改。

**Comment by wf395962475** [comment]
非常感谢提出，稍后测试一下在更新

**Comment by wf395962475** [comment]
已经完成测试并更新
