### ISSUE TITLE
Mac 系统编译报错

### ISSUE THREAD

**Issue by chengjianhong** [CSUcse/CSUthesis#6]
你好，Mac 系统编译时报以下错误：
This is METAFONT, Version 2.71828182 (TeX Live 2021) (preloaded base=mf)
kpathsea: Running mktexmf OT
! I can't find file `OT'. <*> \mode:=ljfour; mag:=1; ; nonstopmode; input OT Please type another input file name ! Emergency stop. <*> \mode:=ljfour; mag:=1; ; nonstopmode; input OT Transcript written on mfput.log.
grep: OT.log: No such file or directory
mktextfm: `mf-nowin -progname=mf \mode:=ljfour; mag:=1; ; nonstopmode; input OT' failed to make OT.tfm.
Process exited with error(s)
![image](https://user-images.githubusercontent.com/12234973/141647866-201123e7-c704-4a8a-b905-49080c00f544.png)

**Comment by wf395962475** [comment]
请使用csuthesis_main.tex测试一下，我们使用是可以的
